### ISSUE TITLE
Non BoneControllers in last UE

### ISSUE THREAD

**Issue by koohz** [ANtlord/LegsIKPlugin#1]
There is not a directory "BoneControllers" in the last UE.

**Comment by ANtlord** [comment]
Excuse me, what do you mean?

**Comment by koohz** [comment]
When build the engine with this plugin, it require some files located in 
"\Engine\Source\Runtime\Engine\Classes\Animation\BoneControllers\"
but in the last build i can't see any BoneControllers folder.

![Image](https://i.gyazo.com/a3b5d8b8e76b1e316a846bf1c4fc99d2.png)

**Comment by ANtlord** [comment]
Hmm, I should check it. I think,  that I could spent for it tomorrow.

**Comment by koohz** [comment]
Nice, here is the compiler log

http://pastebin.com/r2Radfnp

Edit: BoneControllers moved to

"\Engine\Source\Runtime\AnimGraphRuntime\"

**Comment by ANtlord** [comment]
OK, I've got a little free time. It seems, that not only paths have been changed in UE4. I've errors about incorrect types arguments, that I pass. It should be not huge work, but not a little. And I will create two main branches. One for 4.8.x, one for 4.9.x.

**Comment by koohz** [comment]
Well good :D

**Comment by ANtlord** [comment]
I've made branch [unreal-engine-4.9-support](https://github.com/ANtlord/LegsIKPlugin/tree/unreal-engine-4.9-support). It has patched version of plugin, that compiled and works. But on my test project, I've got a bug. It seems, that I get wrong coordinates, but it can be bug of skeleton, that I use. @koMah try it on your skeleton, if you have time.

**Comment by koohz** [comment]
I'm not able to make it work, can you share your node config?

**Comment by ANtlord** [comment]
Node config. Do you mean parameters of node, that available after installation of this plugin?

**Comment by ANtlord** [comment]
Plugin works on Unreal Engine 4.9. Tests on standard new model. Screenshots have been added. Solved.
