### ISSUE TITLE
Unreal Engine 4.10

### ISSUE THREAD

**Issue by agerith** [ANtlord/LegsIKPlugin#3]
Plugin doesn't work with Unreal Engine 4.10.2.

Errors during compile : 
'Runtime/Engine/Classes/Animation/BoneControllers/AnimNode_Fabrik.h' : No such file or directory

**Comment by ANtlord** [comment]
Is it happening on master branch?

**Comment by agerith** [comment]
Yes, I downloaded zip project on master branch

**Comment by ANtlord** [comment]
master branch works only for UE 4.8. Branch unreal-engine-4.9-support will be compiled on 4.10, but the plugin has another issue https://github.com/ANtlord/LegsIKPlugin/issues/2
