### ISSUE TITLE
4.13 Support

### ISSUE THREAD

**Issue by Sorrien** [ANtlord/LegsIKPlugin#4]
I am unable to build my 4.13 project with this plugin enabled. Thanks for reading.

**Comment by ANtlord** [comment]
Hello! Plugin had stoped work from 4.11. The project contains branch unreal-engine-4.11-support where fix of this is in progress. More issues related to new pipeline system of animations. I didn't test the plugin on newer UE4 versions, but I suppose that more of reasons of failed building will be fixed after rework for 4.11.

**Comment by ucotman** [comment]
Hello ANtlord,

I am just curious about the progress on 4.13. Have you managed to solve 4.11 issues?

Kind regards and keep on with the good work!

**Comment by ANtlord** [comment]
Unfortunately no. I have a hard work on my primary job. I fixed compile errors in branch for 4.11 but legs don't move. It necessary to investigate new animation pipeline for fix, but I really have no time for this right now.

**Comment by Mireneye** [comment]
Any update on this? (Or even for 4.14 now). 
Thank you for your hard work!
